
import "./globals.css";
import Navbar from "@/components/Navbar"
import AuthProvider from "@/provider/AuthProvider";
import { Toaster } from 'react-hot-toast';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "@/components/Footer";
import ScrollToTopButton from "@/components/ScrollToTopButton";


export const metadata = {
  title: "INNORA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme='light'>
      <body
        className={`font-mono`}
      >
        <AuthProvider>
          <Toaster
            position="bottom-right"
            reverseOrder={false}
          />
          <Navbar />
          <div className="flex   flex-col bg-[#1c1c1c]">
            <ScrollToTopButton />
            {children}
          </div>
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
